import { afterEach, describe, expect, test } from 'bun:test';
import { EventEmitter } from 'node:events';
import {
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expectThrow } from '../../test/expect-throw';
import { i18nTypes } from './index';

const roots: string[] = [];
afterEach(() => {
	for (const root of roots.splice(0))
		rmSync(root, { recursive: true, force: true });
});

function project(): string {
	const root = mkdtempSync(join(tmpdir(), 'i18n-vue-vite-'));
	roots.push(root);
	mkdirSync(join(root, 'locales'));
	writeFileSync(
		join(root, 'locales/en.json'),
		'{ "home": { "greeting": "Hi {name}" } }',
	);
	writeFileSync(
		join(root, 'locales/fr.json'),
		'{ "home": { "greeting": "Salut {name}" } }',
	);
	return root;
}

type Hooks = {
	configResolved(config: unknown): void;
	buildStart(): void;
	configureServer(server: unknown): void;
};

/** The plugin's hooks, run the way Vite runs them. */
const start = (plugin: unknown, root: string) => {
	const hooks = plugin as Hooks;
	hooks.configResolved({ root });
	hooks.buildStart();
	return hooks;
};

describe('i18nTypes', () => {
	test('writes src/generated/i18n.d.ts from the catalogues when the build starts', () => {
		const root = project();
		start(i18nTypes({ locales: ['en', 'fr'] }), root);
		const types = readFileSync(join(root, 'src/generated/i18n.d.ts'), 'utf8');
		expect(types).toContain("\t\t'home.greeting': { name: string | number };");
		expect(types).toContain("\t\t'fr': true;");
	});

	test('writes where out says', () => {
		const root = project();
		start(i18nTypes({ locales: ['en', 'fr'], out: 'types/i18n.d.ts' }), root);
		expect(readFileSync(join(root, 'types/i18n.d.ts'), 'utf8')).toStartWith(
			'// Generated by @nxgt/i18n-vue',
		);
	});

	test('fails the build on a catalogue that cannot be right', () => {
		const root = project();
		writeFileSync(join(root, 'locales/fr.json'), '{ "home": {} }');
		expectThrow(
			() => start(i18nTypes({ locales: ['en', 'fr'] }), root),
			Error,
			'i18n: fr: home.greeting is missing — en, the fallback locale, has it',
		);
	});

	test('rewrites the types when a catalogue changes in vite dev, and reports a broken one', () => {
		const root = project();
		const hooks = start(i18nTypes({ locales: ['en', 'fr'] }), root);
		const watcher = Object.assign(new EventEmitter(), { add: () => {} });
		const errors: string[] = [];
		hooks.configureServer({
			watcher,
			config: { logger: { error: (message: string) => errors.push(message) } },
		});
		writeFileSync(
			join(root, 'locales/en.json'),
			'{ "home": { "greeting": "Hi {name}", "bye": "Bye" } }',
		);
		writeFileSync(
			join(root, 'locales/fr.json'),
			'{ "home": { "greeting": "Salut {name}", "bye": "Salut" } }',
		);
		watcher.emit('change', join(root, 'locales/fr.json'));
		const file = join(root, 'src/generated/i18n.d.ts');
		expect(readFileSync(file, 'utf8')).toContain("'home.bye': { };");

		writeFileSync(
			join(root, 'locales/fr.json'),
			'{ "home": { "greeting": "Salut {name}" } }',
		);
		watcher.emit('change', join(root, 'locales/fr.json'));
		expect(errors).toEqual([
			'i18n: fr: home.bye is missing — en, the fallback locale, has it',
		]);
		expect(readFileSync(file, 'utf8')).toContain("'home.bye': { };");

		watcher.emit('change', join(root, 'src/main.ts'));
		expect(errors).toHaveLength(1);
	});

	test('refuses a wiring mistake with a TypeError', () => {
		expectThrow(
			() => i18nTypes({ locales: [] }),
			TypeError,
			"i18nTypes: locales must hold at least one locale, as ['en', 'fr']",
		);
		expectThrow(
			() => i18nTypes({ locales: ['en'], out: 'src/i18n.ts' }),
			TypeError,
			'i18nTypes: out must be the path of a .d.ts file, as src/generated/i18n.d.ts',
		);
	});
});
