name: 'Setup'
description: 'Common setup steps for CI jobs'

runs:
  using: 'composite'
  steps:
    # - name: Install Bun
    #   uses: oven-sh/setup-bun@v2
    #   with:
    #     bun-version: latest
    - name: Install dependencies
      run: bun i --frozen-lockfile
      shell: bash
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest