import { afterEach, describe, expect, test } from 'bun:test';
import {
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expectThrow, expectThrowAsync } from '../../test/expect-throw';
import { checkCatalogues } from '../core/catalogues';
import { checkCatalogueSource, loadCatalogues, loadMessages } from './load';
import { typesSource, writeIfChanged, writeTypes } from './types-source';

const dirs: string[] = [];
afterEach(() => {
	for (const dir of dirs.splice(0))
		rmSync(dir, { recursive: true, force: true });
});

/** A project folder holding `files`, by path. */
function project(files: Record<string, string>): string {
	const root = mkdtempSync(join(tmpdir(), 'i18n-vue-'));
	dirs.push(root);
	for (const [path, text] of Object.entries(files)) {
		mkdirSync(join(root, path, '..'), { recursive: true });
		writeFileSync(join(root, path), text);
	}
	return root;
}

const reference = checkCatalogues(
	{
		en: {
			welcome: {
				title: 'Welcome',
				body: 'Hello {name}, {count, plural, one {# seat} other {# seats}} since {at, date}.',
			},
		},
	},
	['en'],
	'en',
).get('en');

describe('typesSource', () => {
	test('declares every key, sorted, with its arguments, and every locale', () => {
		expect(
			typesSource(reference as never, 'en', { locales: ['en', 'fr'] }),
		).toBe(
			[
				'// Generated by @nxgt/i18n-vue from the en catalogue.',
				'// Never edited, never committed: it types t() from the catalogues.',
				"import type {} from '@nxgt/i18n-vue';",
				'',
				"declare module '@nxgt/i18n-vue' {",
				'\tinterface I18nMessages {',
				"\t\t'welcome.body': { at: Date | number; count: number; name: string | number };",
				"\t\t'welcome.title': { };",
				'\t}',
				'\tinterface I18nLocales {',
				"\t\t'en': true;",
				"\t\t'fr': true;",
				'\t}',
				'}',
				'',
			].join('\n'),
		);
	});

	test("fills another module's interface, as @nxgt/mail-i18n's TemplateMessages", () => {
		const source = typesSource(reference as never, 'en', {
			module: '@nxgt/mail-i18n',
			messagesInterface: 'TemplateMessages',
			generator: '@nxgt/mail-i18n',
		});
		expect(source).toStartWith('// Generated by @nxgt/mail-i18n from the en');
		expect(source).toContain("declare module '@nxgt/mail-i18n' {");
		expect(source).toContain('\tinterface TemplateMessages {');
		expect(source).not.toContain('I18nLocales');
	});
});

describe('writeTypes', () => {
	const source = typesSource(reference as never, 'en');

	test('writes, and rewrites only on a change', () => {
		const root = project({});
		const file = join(root, 'src/generated/i18n.d.ts');
		writeTypes(file, 'src/generated/i18n.d.ts', source);
		const first = statSync(file).mtimeMs;
		Bun.sleepSync(20);
		writeIfChanged(file, source);
		expect(statSync(file).mtimeMs).toBe(first);
		const next = typesSource(reference as never, 'en', { locales: ['en'] });
		writeTypes(file, 'x', next);
		expect(readFileSync(file, 'utf8')).toBe(next);
	});

	test('replaces its own file whatever the generator named in it', () => {
		const root = project({});
		const file = join(root, 'types.d.ts');
		const mail = typesSource(reference as never, 'en', {
			module: '@nxgt/mail-i18n',
			messagesInterface: 'TemplateMessages',
			generator: '@nxgt/mail-i18n',
		});
		writeTypes(file, 'types.d.ts', mail);
		writeTypes(file, 'types.d.ts', `${mail}\n`);
		expect(readFileSync(file, 'utf8')).toBe(`${mail}\n`);
	});

	test('refuses to replace a file it did not write, and keeps it', () => {
		const root = project({ 'src/i18n.d.ts': 'declare const mine: 1;\n' });
		expectThrow(
			() => writeTypes(join(root, 'src/i18n.d.ts'), 'src/i18n.d.ts', source),
			Error,
			'i18n: src/i18n.d.ts was not written by @nxgt/i18n-vue — point the types at a file of their own',
		);
		expect(readFileSync(join(root, 'src/i18n.d.ts'), 'utf8')).toBe(
			'declare const mine: 1;\n',
		);
	});
});

describe('loadCatalogues', () => {
	test("reads each locale's file, merges the packages' under it, and checks", async () => {
		const root = project({
			'locales/en.json': '{ "home": { "title": "Home" } }',
			'locales/fr.json': '{ "home": { "title": "Accueil" } }',
		});
		const loaded = await loadCatalogues(root, {
			locales: ['en', 'fr'],
			catalogues: [
				{
					en: { common: { ok: 'OK' } },
					fr: { common: { ok: "D'accord" } },
					de: { common: { ok: 'Gut' } },
				},
			],
		});
		expect(loaded.fallbackLocale).toBe('en');
		expect(loaded.catalogues).toEqual({
			en: { common: { ok: 'OK' }, home: { title: 'Home' } },
			fr: { common: { ok: "D'accord" }, home: { title: 'Accueil' } },
		});
		expect([...loaded.reference.keys()]).toEqual(['common.ok', 'home.title']);
		expect(loaded.files).toEqual([
			join(root, 'locales/en.json'),
			join(root, 'locales/fr.json'),
		]);
		expect(loaded.folders).toEqual([join(root, 'locales')]);
	});

	test('reads another folder, and another fallback locale', async () => {
		const root = project({
			'src/locales/en.json': '{ "a": "A" }',
			'src/locales/fr.json': '{ "a": "A" }',
		});
		const loaded = await loadCatalogues(root, {
			locales: ['en', 'fr'],
			fallbackLocale: 'fr',
			dir: 'src/locales',
		});
		expect(loaded.fallbackLocale).toBe('fr');
	});

	test('throws on a missing file, a file that is not JSON, and a catalogue that cannot be right', async () => {
		const root = project({
			'locales/en.json': '{ "a": "A {name}" }',
			'locales/fr.json': '{ "a": "A {nom}" }',
			'locales/de.json': '{ "a": ',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'it'] }),
			Error,
			'i18n: locales/it.json is missing — every locale has a catalogue',
		);
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'de'] }),
			Error,
			'i18n: locales/de.json is not valid JSON',
		);
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: fr: a uses {nom}, which en does not declare',
		);
	});

	test('reads a folder layout, mixed with a flat file, and nested paths', async () => {
		const root = project({
			'locales/en.json': '{ "home": { "title": "Home" } }',
			'locales/fr.json': '{ "home": { "title": "Accueil" } }',
			'locales/en/mails.json': '{ "welcome": { "subject": "Welcome" } }',
			'locales/fr/mails.json': '{ "welcome": { "subject": "Bienvenue" } }',
			'locales/en/auth/sign-in.json': '{ "title": "Sign in" }',
			'locales/fr/auth/sign-in.json': '{ "title": "Se connecter" }',
		});
		const loaded = await loadCatalogues(root, { locales: ['en', 'fr'] });
		expect(loaded.catalogues.en).toEqual({
			home: { title: 'Home' },
			mails: { welcome: { subject: 'Welcome' } },
			auth: { 'sign-in': { title: 'Sign in' } },
		});
		expect([...loaded.reference.keys()].sort()).toEqual([
			'auth.sign-in.title',
			'home.title',
			'mails.welcome.subject',
		]);
		expect(loaded.files).toEqual([
			join(root, 'locales/en.json'),
			join(root, 'locales/en/auth/sign-in.json'),
			join(root, 'locales/en/mails.json'),
			join(root, 'locales/fr.json'),
			join(root, 'locales/fr/auth/sign-in.json'),
			join(root, 'locales/fr/mails.json'),
		]);
		expect(loaded.folders).toEqual([
			join(root, 'locales'),
			join(root, 'locales/en'),
			join(root, 'locales/fr'),
		]);
	});

	test('reads a folder-only locale, with no flat file at all', async () => {
		const root = project({
			'locales/en/mails.json': '{ "title": "Mail" }',
			'locales/fr/mails.json': '{ "title": "Courriel" }',
		});
		const loaded = await loadCatalogues(root, { locales: ['en', 'fr'] });
		expect(loaded.catalogues).toEqual({
			en: { mails: { title: 'Mail' } },
			fr: { mails: { title: 'Courriel' } },
		});
	});

	test('throws on a key from the flat file colliding with a file prefix', async () => {
		const root = project({
			'locales/en.json': '{ "mails": { "title": "Mail" } }',
			'locales/fr.json': '{ "mails": { "title": "Courriel" } }',
			'locales/en/mails.json': '{ "title": "Mail again" }',
			'locales/fr/mails.json': '{ "title": "Courriel encore" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: en: mails is defined by both locales/en.json and locales/en/mails.json',
		);
	});

	test('throws on two files defining the same prefix', async () => {
		const root = project({
			'locales/en.json': '{}',
			'locales/fr.json': '{}',
			'locales/en/mails.json': '{ "welcome": "Welcome" }',
			'locales/en/mails/welcome.json': '{ "title": "Hi" }',
			'locales/fr/mails.json': '{ "welcome": "Bienvenue" }',
			'locales/fr/mails/welcome.json': '{ "title": "Salut" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: en: mails is defined by both locales/en/mails.json and locales/en/mails/welcome.json',
		);
	});

	test('throws on a second file reaching inside a first file, even without a matching leaf name', async () => {
		// en/mails.json placed { welcome: 'Hi' } whole at `mails`: a sibling key
		// from another file is still a collision, not a silent addition.
		const root = project({
			'locales/en.json': '{}',
			'locales/fr.json': '{}',
			'locales/en/mails.json': '{ "welcome": "Hi" }',
			'locales/en/mails/subject.json': '{ "line1": "Hello" }',
			'locales/fr/mails.json': '{ "welcome": "Salut" }',
			'locales/fr/mails/subject.json': '{ "line1": "Bonjour" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: en: mails is defined by both locales/en/mails.json and locales/en/mails/subject.json',
		);
	});

	test('throws on a folder file reaching inside an object the flat file itself declared', async () => {
		// locales/en.json's own `mails` object is sealed exactly like a folder
		// file's: locales/en/mails/subject.json may not add a sibling to it.
		const root = project({
			'locales/en.json': '{ "mails": { "title": "Flat mail title" } }',
			'locales/fr.json': '{ "mails": { "title": "Titre du courriel" } }',
			'locales/en/mails/subject.json': '{ "line1": "Subject line" }',
			'locales/fr/mails/subject.json': '{ "line1": "Ligne de sujet" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: en: mails is defined by both locales/en.json and locales/en/mails/subject.json',
		);
	});

	test('throws on a file present in a locale but not the fallback locale', async () => {
		const root = project({
			'locales/en.json': '{}',
			'locales/fr.json': '{}',
			'locales/fr/extra.json': '{ "title": "Titre" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: locales/fr/extra.json exists, and locales/en/extra.json does not — every locale has the same files',
		);
	});

	test('throws on a file the fallback locale has that another locale does not', async () => {
		const root = project({
			'locales/en.json': '{}',
			'locales/fr.json': '{}',
			'locales/en/extra.json': '{ "title": "Title" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: locales/fr/extra.json is missing — locales/en/extra.json exists',
		);
	});

	test('throws on a bad path segment, naming the file', async () => {
		const root = project({
			'locales/en.json': '{}',
			'locales/fr.json': '{}',
			'locales/en/sign_in.json': '{ "title": "Sign in" }',
			'locales/fr/sign_in.json': '{ "title": "Se connecter" }',
		});
		await expectThrowAsync(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: locales/en/sign_in.json: sign_in is not camelCase or kebab-case — a file path segment is a key segment too, as mails or sign-in',
		);
	});
});

describe('loadMessages', () => {
	test('runs the default export, or the function it exports, and answers it as a resources object', async () => {
		const root = project({
			'i18n/messages.ts': [
				"export default { en: { a: 'A' }, fr: { a: 'A' } };",
			].join('\n'),
			'i18n/factory.ts': [
				"export default () => ({ en: { a: 'A' }, fr: { a: 'A' } });",
			].join('\n'),
		});
		const direct = await loadMessages(root, 'i18n/messages.ts', ['en', 'fr']);
		expect(direct.catalogues).toEqual({ en: { a: 'A' }, fr: { a: 'A' } });
		expect(direct.files).toEqual([join(root, 'i18n/messages.ts')]);
		expect(direct.folders).toEqual([]);
		const factory = await loadMessages(root, 'i18n/factory.ts', ['en', 'fr']);
		expect(factory.catalogues).toEqual({ en: { a: 'A' }, fr: { a: 'A' } });
	});

	test('loadCatalogues reads the same source as the app would import', async () => {
		const root = project({
			'i18n/messages.ts': [
				"export default { en: { a: 'A {name}' }, fr: { a: 'A {nom}' } };",
			].join('\n'),
		});
		await expectThrowAsync(
			() =>
				loadCatalogues(root, {
					locales: ['en', 'fr'],
					messages: 'i18n/messages.ts',
				}),
			Error,
			'i18n: fr: a uses {nom}, which en does not declare',
		);
	});

	test('throws naming the module for no default export, a bad shape, or a missing locale', async () => {
		const root = project({
			'i18n/none.ts': 'export const a = 1;',
			'i18n/bad.ts': 'export default 1;',
			'i18n/incomplete.ts': "export default { en: { a: 'A' } };",
		});
		await expectThrowAsync(
			() => loadMessages(root, 'i18n/none.ts', ['en']),
			Error,
			'i18n: i18n/none.ts has no default export — export the resources object, or a function that returns it',
		);
		await expectThrowAsync(
			() => loadMessages(root, 'i18n/bad.ts', ['en']),
			Error,
			"i18n: i18n/bad.ts's default export must be a resources object ({ en: {...}, fr: {...} }) or a function that returns one",
		);
		await expectThrowAsync(
			() => loadMessages(root, 'i18n/incomplete.ts', ['en', 'fr']),
			Error,
			'i18n: i18n/incomplete.ts is missing the fr locale',
		);
	});

	test('ignores a locale the resources object has that locales does not ask for', async () => {
		const root = project({
			'i18n/messages.ts': [
				"export default { en: { a: 'A' }, fr: { a: 'A' }, de: { a: 'A' } };",
			].join('\n'),
		});
		const loaded = await loadMessages(root, 'i18n/messages.ts', ['en', 'fr']);
		expect(Object.keys(loaded.catalogues).sort()).toEqual(['en', 'fr']);
		const full = await loadCatalogues(root, {
			locales: ['en', 'fr'],
			messages: 'i18n/messages.ts',
		});
		expect(Object.keys(full.catalogues).sort()).toEqual(['en', 'fr']);
	});

	test('names the module when it cannot be imported, or its function throws', async () => {
		const root = project({
			'i18n/broken.ts': 'export default {{{',
			'i18n/throws.ts': [
				"export default () => { throw new Error('nope'); };",
			].join('\n'),
		});
		const brokenError = await loadMessages(root, 'i18n/broken.ts', [
			'en',
		]).catch((error: unknown) => error);
		expect(brokenError).toBeInstanceOf(Error);
		expect((brokenError as Error).message).toStartWith(
			'i18n: i18n/broken.ts could not be loaded (',
		);
		await expectThrowAsync(
			() => loadMessages(root, 'i18n/throws.ts', ['en']),
			Error,
			"i18n: i18n/throws.ts's default export could not be run (nope)",
		);
	});
});

describe('checkCatalogueSource', () => {
	const fails = (options: unknown, message: string) =>
		expectThrow(
			() => checkCatalogueSource('i18nTypes', options),
			TypeError,
			message,
		);

	test('refuses a wiring mistake with a TypeError naming the caller', () => {
		fails(
			null,
			"i18nTypes: options must be an object, as { locales: ['en', 'fr'] }",
		);
		fails(
			{ locales: [] },
			"i18nTypes: locales must hold at least one locale, as ['en', 'fr']",
		);
		fails(
			{ locales: ['en', 'English'] },
			'i18nTypes: locales holds something that is not a locale — write each as a BCP 47 tag, as en or pt-BR',
		);
		fails(
			{ locales: ['en', 'en'] },
			'i18nTypes: locales holds the same locale twice',
		);
		fails(
			{ locales: ['en'], fallbackLocale: 'fr' },
			'i18nTypes: fallbackLocale must be one of locales',
		);
		fails(
			{ locales: ['en'], dir: '' },
			'i18nTypes: dir must be a folder of the project',
		);
		fails(
			{ locales: ['en'], catalogues: { en: {} } },
			'i18nTypes: catalogues must be a list of catalogues by locale, as [{ en: {...}, fr: {...} }]',
		);
		fails(
			{ locales: ['en'], messages: '' },
			"i18nTypes: messages must be a module path, as './i18n/messages.ts'",
		);
		fails(
			{ locales: ['en'], messages: 1 },
			"i18nTypes: messages must be a module path, as './i18n/messages.ts'",
		);
		fails(
			{ locales: ['en'], dir: 'locales', messages: './i18n/messages.ts' },
			'i18nTypes: dir and messages cannot both be set — messages replaces the folder',
		);
		expect(() =>
			checkCatalogueSource('i18nTypes', {
				locales: ['en', 'pt-BR'],
				fallbackLocale: 'pt-BR',
				dir: 'src/locales',
				catalogues: [{ en: {} }],
			}),
		).not.toThrow();
		expect(() =>
			checkCatalogueSource('i18nTypes', {
				locales: ['en'],
				messages: './i18n/messages.ts',
			}),
		).not.toThrow();
	});
});
