import { afterEach, describe, expect, test } from 'bun:test';
import {
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	statSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expectThrow } from '../../test/expect-throw';
import { checkCatalogues } from '../core/catalogues';
import { checkCatalogueSource, loadCatalogues } from './load';
import { typesSource, writeIfChanged, writeTypes } from './types-source';

const dirs: string[] = [];
afterEach(() => {
	for (const dir of dirs.splice(0))
		rmSync(dir, { recursive: true, force: true });
});

/** A project folder holding `files`, by path. */
function project(files: Record<string, string>): string {
	const root = mkdtempSync(join(tmpdir(), 'i18n-vue-'));
	dirs.push(root);
	for (const [path, text] of Object.entries(files)) {
		mkdirSync(join(root, path, '..'), { recursive: true });
		writeFileSync(join(root, path), text);
	}
	return root;
}

const reference = checkCatalogues(
	{
		en: {
			welcome: {
				title: 'Welcome',
				body: 'Hello {name}, {count, plural, one {# seat} other {# seats}} since {at, date}.',
			},
		},
	},
	['en'],
	'en',
).get('en');

describe('typesSource', () => {
	test('declares every key, sorted, with its arguments, and every locale', () => {
		expect(
			typesSource(reference as never, 'en', { locales: ['en', 'fr'] }),
		).toBe(
			[
				'// Generated by @nxgt/i18n-vue from the en catalogue.',
				'// Never edited, never committed: it types t() from the catalogues.',
				"import type {} from '@nxgt/i18n-vue';",
				'',
				"declare module '@nxgt/i18n-vue' {",
				'\tinterface I18nMessages {',
				"\t\t'welcome.body': { at: Date | number; count: number; name: string | number };",
				"\t\t'welcome.title': { };",
				'\t}',
				'\tinterface I18nLocales {',
				"\t\t'en': true;",
				"\t\t'fr': true;",
				'\t}',
				'}',
				'',
			].join('\n'),
		);
	});

	test("fills another module's interface, as @nxgt/mail-i18n's TemplateMessages", () => {
		const source = typesSource(reference as never, 'en', {
			module: '@nxgt/mail-i18n',
			messagesInterface: 'TemplateMessages',
			generator: '@nxgt/mail-i18n',
		});
		expect(source).toStartWith('// Generated by @nxgt/mail-i18n from the en');
		expect(source).toContain("declare module '@nxgt/mail-i18n' {");
		expect(source).toContain('\tinterface TemplateMessages {');
		expect(source).not.toContain('I18nLocales');
	});
});

describe('writeTypes', () => {
	const source = typesSource(reference as never, 'en');

	test('writes, and rewrites only on a change', () => {
		const root = project({});
		const file = join(root, 'src/generated/i18n.d.ts');
		writeTypes(file, 'src/generated/i18n.d.ts', source);
		const first = statSync(file).mtimeMs;
		Bun.sleepSync(20);
		writeIfChanged(file, source);
		expect(statSync(file).mtimeMs).toBe(first);
		const next = typesSource(reference as never, 'en', { locales: ['en'] });
		writeTypes(file, 'x', next);
		expect(readFileSync(file, 'utf8')).toBe(next);
	});

	test('replaces its own file whatever the generator named in it', () => {
		const root = project({});
		const file = join(root, 'types.d.ts');
		const mail = typesSource(reference as never, 'en', {
			module: '@nxgt/mail-i18n',
			messagesInterface: 'TemplateMessages',
			generator: '@nxgt/mail-i18n',
		});
		writeTypes(file, 'types.d.ts', mail);
		writeTypes(file, 'types.d.ts', `${mail}\n`);
		expect(readFileSync(file, 'utf8')).toBe(`${mail}\n`);
	});

	test('refuses to replace a file it did not write, and keeps it', () => {
		const root = project({ 'src/i18n.d.ts': 'declare const mine: 1;\n' });
		expectThrow(
			() => writeTypes(join(root, 'src/i18n.d.ts'), 'src/i18n.d.ts', source),
			Error,
			'i18n: src/i18n.d.ts was not written by @nxgt/i18n-vue — point the types at a file of their own',
		);
		expect(readFileSync(join(root, 'src/i18n.d.ts'), 'utf8')).toBe(
			'declare const mine: 1;\n',
		);
	});
});

describe('loadCatalogues', () => {
	test("reads each locale's file, merges the packages' under it, and checks", () => {
		const root = project({
			'locales/en.json': '{ "home": { "title": "Home" } }',
			'locales/fr.json': '{ "home": { "title": "Accueil" } }',
		});
		const loaded = loadCatalogues(root, {
			locales: ['en', 'fr'],
			catalogues: [
				{
					en: { common: { ok: 'OK' } },
					fr: { common: { ok: "D'accord" } },
					de: { common: { ok: 'Gut' } },
				},
			],
		});
		expect(loaded.fallbackLocale).toBe('en');
		expect(loaded.catalogues).toEqual({
			en: { common: { ok: 'OK' }, home: { title: 'Home' } },
			fr: { common: { ok: "D'accord" }, home: { title: 'Accueil' } },
		});
		expect([...loaded.reference.keys()]).toEqual(['common.ok', 'home.title']);
	});

	test('reads another folder, and another fallback locale', () => {
		const root = project({
			'src/locales/en.json': '{ "a": "A" }',
			'src/locales/fr.json': '{ "a": "A" }',
		});
		const loaded = loadCatalogues(root, {
			locales: ['en', 'fr'],
			fallbackLocale: 'fr',
			dir: 'src/locales',
		});
		expect(loaded.fallbackLocale).toBe('fr');
	});

	test('throws on a missing file, a file that is not JSON, and a catalogue that cannot be right', () => {
		const root = project({
			'locales/en.json': '{ "a": "A {name}" }',
			'locales/fr.json': '{ "a": "A {nom}" }',
			'locales/de.json': '{ "a": ',
		});
		expectThrow(
			() => loadCatalogues(root, { locales: ['en', 'it'] }),
			Error,
			'i18n: locales/it.json is missing — every locale has a catalogue',
		);
		expectThrow(
			() => loadCatalogues(root, { locales: ['en', 'de'] }),
			Error,
			'i18n: locales/de.json is not valid JSON',
		);
		expectThrow(
			() => loadCatalogues(root, { locales: ['en', 'fr'] }),
			Error,
			'i18n: fr: a uses {nom}, which en does not declare',
		);
	});
});

describe('checkCatalogueSource', () => {
	const fails = (options: unknown, message: string) =>
		expectThrow(
			() => checkCatalogueSource('i18nTypes', options),
			TypeError,
			message,
		);

	test('refuses a wiring mistake with a TypeError naming the caller', () => {
		fails(
			null,
			"i18nTypes: options must be an object, as { locales: ['en', 'fr'] }",
		);
		fails(
			{ locales: [] },
			"i18nTypes: locales must hold at least one locale, as ['en', 'fr']",
		);
		fails(
			{ locales: ['en', 'English'] },
			'i18nTypes: locales holds something that is not a locale — write each as a BCP 47 tag, as en or pt-BR',
		);
		fails(
			{ locales: ['en', 'en'] },
			'i18nTypes: locales holds the same locale twice',
		);
		fails(
			{ locales: ['en'], fallbackLocale: 'fr' },
			'i18nTypes: fallbackLocale must be one of locales',
		);
		fails(
			{ locales: ['en'], dir: '' },
			'i18nTypes: dir must be a folder of the project',
		);
		fails(
			{ locales: ['en'], catalogues: { en: {} } },
			'i18nTypes: catalogues must be a list of catalogues by locale, as [{ en: {...}, fr: {...} }]',
		);
		expect(() =>
			checkCatalogueSource('i18nTypes', {
				locales: ['en', 'pt-BR'],
				fallbackLocale: 'pt-BR',
				dir: 'src/locales',
				catalogues: [{ en: {} }],
			}),
		).not.toThrow();
	});
});
