import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { ArgumentKind, Messages } from '../core/catalogues';
import { keyVariants } from '../core/keys';

/** The second line of every generated file, whatever its generator: how `writeTypes` knows a file is one. */
const MARKER =
	'// Never edited, never committed: it types t() from the catalogues.';

/** What `t` accepts for each kind — as `checkArguments` checks it. */
const TYPE_OF: Readonly<Record<ArgumentKind, string>> = {
	string: 'string | number',
	number: 'number',
	date: 'Date | number',
};

/** Which module and interfaces the generated file fills. */
export interface TypesSourceOptions {
	/** The module augmented. Default `'@nxgt/i18n-vue'`. */
	readonly module?: string;
	/** The interface of the keys and their arguments. Default `'I18nMessages'`. */
	readonly messagesInterface?: string;
	/** The locales written to `I18nLocales`, or `false` for none. Default none. */
	readonly locales?: readonly string[] | false;
	/** Who wrote the file, for its first line. Default `'@nxgt/i18n-vue'`. */
	readonly generator?: string;
}

const byName = ([a]: [string, unknown], [b]: [string, unknown]) =>
	a < b ? -1 : a > b ? 1 : 0;

/**
 * The declaration file that types `t`: each key of the `reference`
 * catalogue, with its arguments — so an editor completes a key and flags an
 * unknown one or a missing argument — and each locale, so `setLocale('de')`
 * is a type error. Keys, names and locales are checked before this runs, so
 * they are safe to write quoted.
 *
 * A key types under both conventions: a catalogue written `signIn` also
 * types `sign-in`, and one written `sign-in` also types `signIn` — `t()`
 * accepts either at runtime (`keyVariants`), so the generated types accept
 * either too.
 */
export function typesSource(
	reference: Messages,
	fallbackLocale: string,
	options: TypesSourceOptions = {},
): string {
	const module = options.module ?? '@nxgt/i18n-vue';
	const generator = options.generator ?? '@nxgt/i18n-vue';
	const seen = new Set<string>();
	const entries: Array<{ key: string; args: string[] }> = [];
	for (const [key, message] of reference.entries()) {
		const args = [...message.args.entries()]
			.sort(byName)
			.map(([name, kind]) => `${name}: ${TYPE_OF[kind]}`);
		for (const variant of keyVariants(key)) {
			if (seen.has(variant)) continue;
			seen.add(variant);
			entries.push({ key: variant, args });
		}
	}
	entries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
	const messages = entries.map(
		({ key, args }) =>
			`\t\t'${key}': { ${args.join('; ')}${args.length > 0 ? ' ' : ''}};`,
	);
	const locales = options.locales || [];
	return [
		`// Generated by ${generator} from the ${fallbackLocale} catalogue.`,
		MARKER,
		`import type {} from '${module}';`,
		'',
		`declare module '${module}' {`,
		`\tinterface ${options.messagesInterface ?? 'I18nMessages'} {`,
		...messages,
		'\t}',
		...(locales.length > 0
			? [
					'\tinterface I18nLocales {',
					...locales.map((locale) => `\t\t'${locale}': true;`),
					'\t}',
				]
			: []),
		'}',
		'',
	].join('\n');
}

/** Writes `source` to `file` only when it changed, so an editor or a watcher sees a change only where there is one. */
export function writeIfChanged(file: string, source: string): void {
	if (existsSync(file) && readFileSync(file, 'utf8') === source) return;
	mkdirSync(dirname(file), { recursive: true });
	writeFileSync(file, source);
}

/**
 * Writes the generated types to `file`, shown as `path` — unless `file` holds
 * something `typesSource` did not write, whatever its `generator`: that **throws**, and the file is kept.
 */
export function writeTypes(file: string, path: string, source: string): void {
	const lines = existsSync(file)
		? readFileSync(file, 'utf8').split('\n', 2)
		: null;
	if (
		lines !== null &&
		!(lines[0]?.startsWith('// Generated by ') && lines[1] === MARKER)
	) {
		throw new Error(
			`i18n: ${path} was not written by @nxgt/i18n-vue — point the types at a file of their own`,
		);
	}
	writeIfChanged(file, source);
}
