export const EMOJI_I18N_KEYS = {
	en: {
		all: 'All',
		recent: 'Recently Used',
		general: 'General',
		people_body: 'People & Body',
		components: 'Components',
		animals_nature: 'Animals & Nature',
		food_drink: 'Food & Drink',
		travel_places: 'Travel & Places',
		activities: 'Activities',
		objects: 'Objects',
		symbols: 'Symbols',
		flags: 'Flags',
	},
	fr: {
		all: 'Tous',
		recent: 'Récemment utilisés',
		general: 'Général',
		people_body: 'Personnes & corps',
		components: 'Composants',
		animals_nature: 'Animaux & nature',
		food_drink: 'Nourriture & boissons',
		travel_places: 'Voyages & lieux',
		activities: 'Activités',
		objects: 'Objets',
		symbols: 'Symboles',
		flags: 'Drapeaux',
	},
};
