import type { Catalogue } from '../core/catalogues';
import { STATE_KEY } from './state-key';

export { STATE_KEY } from './state-key';

/** A year, in seconds: how long the cookie of a chosen locale lasts. */
const COOKIE_MAX_AGE = 60 * 60 * 24 * 365;

/** What the generated plugin is made from. */
export interface PluginSourceOptions {
	readonly catalogues: Readonly<Record<string, Catalogue>>;
	readonly fallbackLocale: string;
	readonly cookie: string;
}

/**
 * The Nuxt plugin the module adds, as source: it passes Nuxt's composables to
 * `setupNuxtI18n`, installs the i18n, and sets `<html lang>`. Generated
 * rather than shipped, because it imports `#imports`, which exists only
 * inside a Nuxt build. The catalogues are inlined as JSON: they were checked
 * when the module ran.
 */
export function pluginSource(options: PluginSourceOptions): string {
	return [
		'// Generated by @nxgt/i18n-vue/nuxt. Never edited.',
		"import { defineNuxtPlugin, useCookie, useHead, useRequestHeaders, useState } from '#imports';",
		"import { setupNuxtI18n } from '@nxgt/i18n-vue/nuxt/runtime';",
		'',
		`const catalogues = ${JSON.stringify(options.catalogues)};`,
		'',
		'export default defineNuxtPlugin({',
		"\tname: '@nxgt/i18n-vue',",
		"\tenforce: 'pre',",
		'\tsetup(nuxtApp) {',
		'\t\tconst i18n = setupNuxtI18n({',
		'\t\t\tcatalogues,',
		`\t\t\tfallbackLocale: ${JSON.stringify(options.fallbackLocale)},`,
		`\t\t\tcookie: useCookie(${JSON.stringify(options.cookie)}, { path: '/', sameSite: 'lax', maxAge: ${COOKIE_MAX_AGE} }),`,
		`\t\t\tstate: useState(${JSON.stringify(STATE_KEY)}),`,
		'\t\t\trequested: () =>',
		'\t\t\t\timport.meta.server',
		"\t\t\t\t\t? useRequestHeaders(['accept-language'])['accept-language']",
		"\t\t\t\t\t: typeof navigator === 'undefined' ? null : navigator.languages,",
		'\t\t});',
		'\t\tnuxtApp.vueApp.use(i18n);',
		'\t\tuseHead({ htmlAttrs: { lang: i18n.locale } });',
		'\t},',
		'});',
		'',
	].join('\n');
}
