name: CI

on:
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    name: CI
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint code
        run: biome ci
      - name: Type checking
        run: bun run typecheck
      - name: Run tests
        run: bun test
      - name: Build packages
        run: bun run build
